rtl8192ce-objs :=		\
		dm.o		\
		fw.o		\
		hw.o		\
		led.o		\
		phy.o		\
		rf.o		\
		sw.o		\
		table.o		\
		trx.o

obj-m += rtl8192ce.o

ccflags-y += -Idrivers/net/wireless/rtlwifi -D__CHECK_ENDIAN__

