rtl8821ae-objs :=		\
		dm.o		\
		fw.o		\
		hw.o		\
		led.o		\
		phy.o		\
		pwrseq.o	\
		pwrseqcmd.o	\
		rf.o		\
		sw.o		\
		table.o		\
		trx.o		\


obj-m += rtl8821ae.o

ccflags-y += -D__CHECK_ENDIAN__
