# SPDX-License-Identifier: GPL-2.0
btcoexist-objs :=	halbtc8192e2ant.o	\
			halbtc8723b1ant.o	\
			halbtc8723b2ant.o	\
			halbtc8821a1ant.o	\
			halbtc8821a2ant.o	\
			halbtc8822b1ant.o	\
			halbtc8822b2ant.o	\
			halbtc8822bwifionly.o	\
			halbtc8723d1ant.o	\
			halbtc8723d2ant.o	\
			halbtcoutsrc.o		\
			rtl_btc.o

obj-m += btcoexist.o
